### ISSUE TITLE
How to modify link on confirmation page ?

### ISSUE THREAD

**Issue by JpE-fr** [paylike/plugin-hikashop#4]
Hello,
I want to use paylike with hikashop and I would like to know how to modify the order history link on the confirmation page after payment please ?
The current link sends to cart and I would like it sends to commands
Thanks for your help,
Best regards

**Comment by ionutcalara** [comment]
Hi @JpE-fr, I think it should go to orders by default, so we're going to have a look and push an update with the fix.

**Comment by ionutcalara** [comment]
Hi @JpE-fr, I have checked the link and it seems that it will redirect to the user panel, if that link exists on hikashop: https://share.getcloudapp.com/rRulBDpj . Make sure that a link that points to 'com_hikashop&view=user&layout=cpanel' exists under the hikashop menu and it will redirect to the orders. 

I am closing this ticket, but feel free to reopen.
