### ISSUE TITLE
Support PHP8

### ISSUE THREAD

**Issue by hikashop-nicolas** [paylike/plugin-hikashop#6]
An error has been reported regarding PHP 8 support in the plugin:
https://www.hikashop.com/forum/payment-methods/903679-paylike-plugin-error-argument-2-array-must-be-of-type-array-string-given.html#338023
This error can be fixed changing the line:
"custom"=>implode($customs, "\n"),
to:
"custom"=>implode("\n", $customs),
but there might be other issues with PHP8.

**Comment by cosminbosutar** [comment]
Hello @hikashop-nicolas,

Thank you for mentioning this!

We'll have test the plugin with PHP 8 and the rest of the mentioned configuration and come back with a fix.

**Comment by hikashop-nicolas** [comment]
Thanks !

Note that Joomla 4 has been released a few months ago and I can see that you have some code which doesn't work on Joomla 4 (for example you use JRequest which has been removed in Joomla 4).
So while you test the plugin with PHP8, I would recommend doing it with Joomla 4 so that you can hit two birds with one stone.

**Comment by hsimaer-fdbi** [comment]
Hi,

Have you been able to advance on the subject ?
Actually only the PHP version 7.4 is still supported and compatible with your plugin.

We wanted to test Paylike for our future website with Hikashop (Joomla 4 + PHP >= 8), but it's a bit blocking for the moment.

**Comment by cosminbosutar** [comment]
Hello @hsimaer-fdbi,

We started looking on this bug an I will come back with an update the following days.
Also, we are using the versions that you specified in the HikaShop thread:
-- HikaShop version -- : 4.4.4
-- Joomla version -- : 4.0.5
-- PHP version -- : 8.0.12

Can you please confirm you are using the same versions?

**Comment by hsimaer-fdbi** [comment]
Hi, thanks for your answer.

Yes, I use these versions.

**Comment by cosminbosutar** [comment]
Hello @hsimaer-fdbi,

Here is an updated version of the plugin that includes the fix and was tested with the following versions;
-- HikaShop version -- : 4.4.5
-- Joomla version -- : 4.0.5
-- PHP version -- : 8.0.12

Please use this version of the plugin.

[plugin-hikashop.zip](https://github.com/paylike/plugin-hikashop/files/7855381/plugin-hikashop.zip)

**Comment by hsimaer-fdbi** [comment]
Thanks a lot, I will try this.

**Comment by ionutcalara** [comment]
Hi @hsimaer-fdbi were you able to test the provided zip? Did you have any issues?

**Comment by hsimaer-fdbi** [comment]
Hi,

Sorry for the delay.

I installed your file and tested only few times the payment.
No issue encountered for the moment,

My tests will probably be more significant this week or maybe the next.

In any case, I will get back to you.

**Comment by cosminbosutar** [comment]
@ionutcalara we can close this issue as it has been solved.
